import "./globals.css"; 
import type { Metadata } from "next";
// ADICIONE Geist_Mono AQUI EMBAIXO:
import { Geist, Geist_Mono } from "next/font/google"; 

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

// AGORA O Geist_Mono SERÁ RECONHECIDO:
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
